const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c=vm.createContext({console,TextEncoder,Uint8Array,DataView,Map,Date,Number,JSON,Blob});
vm.runInContext(fs.readFileSync('web/estate-export.js','utf8')+'\n'+fs.readFileSync('web/xlsx-export.js','utf8'),c);
const run=s=>vm.runInContext(s,c);
run(`globalThis.item={region:{code:'1',sido_name:'서울',gu_name:'가구',dong_name:'가동'},building:{key:'가구 가동 1 같은이름 | 84㎡',complex_key:'가구 가동 1 같은이름',building_name:'같은이름',area_type:'전용 84㎡ (25.4평)',built_year:1994,households:100,count:8,metrics:{price_billion:{median:11.3}},elementary_500m:true}};
globalThis.second={region:item.region,building:{...item.building,key:'가구 가동 2 같은이름 | 84㎡',complex_key:'가구 가동 2 같은이름'}};
globalThis.type2={region:item.region,building:{...item.building,key:'가구 가동 1 같은이름 | 59㎡',area_type:'전용 59㎡ (17.8평)'}};
globalThis.profile=EstateExport.empty();profile.destinations[0].name='직장 예시';
profile.routes[EstateExport.key(item)]={groom_work:{destination:'직장 예시',mode:'transit',day:'weekday',departure_time:'08:00',minutes:35,observed_at:'2026-10-08T00:00:00+09:00',source_url:'https://map.naver.com/p/directions/example'}};
globalThis.sheets=EstateExport.sheets([item,type2,second],{year:'2026',currentYear:2026,profile});`);
assert.equal(run('sheets.length'),2,'One practical sheet plus sources');
assert.equal(run('sheets[0].rows.length'),3,'All exact types and distinct parcels survive');
assert.equal(run('sheets[0].rows[0][12].result'),32);
assert.equal(run('sheets[0].rows[0][24]'),35);
assert.equal(run('sheets[0].rows[2][24]'),null,'Never borrow a route from a similarly named complex');
assert.equal(run('sheets[0].rows[0][28]'),null,'Visit cells must be blank');
assert.equal(run('sheets[0].rows[0][29]'),null,'Memo cells must be blank');
assert.equal(run('sheets[0].rows[0][16]'),null,'Do not infer land share');
assert.equal(run('sheets[0].rows[0][19]'),'O');
assert.equal(run('sheets[0].rows[0][13]'),null,'Missing parking must not become zero');
assert.equal(run('sheets[0].rows[0][8]'),null,'Observed transactions must never become asking prices');
assert.equal(run('sheets[0].rows[0][6]'),null,'Legacy intervals are not direct quantiles');
assert.equal(run(`sheets[0].columns.some(c=>/식별|키|확인 상태/.test(c.label))`),false);
assert.equal(run(`sheets[0].rows.some(r=>r.includes('미확인'))`),false);
run(`globalThis.directSheets=EstateExport.sheets([item],{profile,year:'2026',recommendationFor:()=>({current_valuation:{status:'available',price_billion:10,quantiles:{status:'available',prices_billion:{p10:7,p50:10,p90:12}}}})});`);
assert.deepEqual(Array.from(run('directSheets[0].rows[0].slice(5,8)')),[10,7,12]);
run(`profile.destinations[0].name='변경된 직장';`);
assert.equal(run(`EstateExport.route(profile,item,'groom_work')`),null,'Changed destination invalidates cached travel times');
run(`profile.destinations[0].name='직장 예시';profile.routes[EstateExport.key(item)].groom_work.departure_time='10:00';`);
assert.equal(run(`EstateExport.route(profile,item,'groom_work')`),null,'Do not mix departure scenarios');
run(`profile.routes[EstateExport.key(item)].groom_work.departure_time='08:00';profile.routes[EstateExport.key(item)].groom_work.source_url='https://example.com/';`);
assert.equal(run(`EstateExport.route(profile,item,'groom_work')`),null,'Require actual Naver provenance');
assert.throws(()=>run(`EstateExport.validate({...profile,departure:{day:'weekend',time:'08:00',mode:'transit'}})`));
const bytes=run('EstateXlsx.build(sheets)');assert.equal(Buffer.from(bytes).readUInt32LE(0),0x04034b50);
assert.equal(run('EstateXlsx.col(33)'),'AH');
const hostile=Buffer.from(run(`EstateXlsx.build([{name:'safe',columns:[{label:'name'}],rows:[['=HYPERLINK("x")'],['<script>']]}])`)).toString();
assert.ok(hostile.includes('t="inlineStr"'));assert.ok(!hostile.includes('<f>'));assert.ok(hostile.includes('&lt;script&gt;'));
if(process.argv[2])fs.writeFileSync(process.argv[2],bytes);
console.log('Excel export: grouping, complete rows, blank fields, route conditions, safe text and XLSX structure passed.');
